swagger: "2.0"
info:
  title: Heracles
  version: 1.0.0
  description: Heracles is a web app that converts money into a string format.
host: 127.0.0.1:9393
externalDocs:
  description: GitHub README
  url: "https://github.com/skambo/heracles/blob/master/README.md"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/formatAmount:
    post:
      summary: Convert amount (sum of money represented in a standardized object) into a string format.
      description: Convert amount (sum of money represented in a standardized object) into a string format.
      parameters:
        - in: body
          name: formatAmountRequest
          required: true
          schema:
            $ref: "#/definitions/FormatAmountRequest"

      responses:
        "200":
          description: Format Amount Success
          schema:
            $ref: "#/definitions/FormatAmountResponse"
        "400":
          description: Request Rejected
          schema:
            $ref: "#/definitions/FormatAmountResponse"
        "401":
          description: Request Unauthorized
          schema:
            $ref: "#/definitions/FormatAmountResponse"
        "500":
          description: Format Amount Failed
          schema:
            $ref: "#/definitions/FormatAmountResponse"

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization

definitions:
  FormatAmountRequest:
    type: object
    properties:
      amount:
        type: number
    required:
      - amount

  FormatAmountResponse:
    type: object
    properties:
      result:
        type: string